-- 코드를 입력하세요
SELECT A.CART_ID
FROM (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME = '우유') A
JOIN (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME = '요거트') B
ON A.CART_ID = B.CART_ID
ORDER BY A.CART_ID