-- 코드를 입력하세요
SET @var := -1;
SELECT TEMP.HOUR, IFNULL(O.COUNT,0) AS COUNT
FROM (SELECT @var := @var+1 as HOUR FROM ANIMAL_OUTS) TEMP
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) O
ON TEMP.HOUR = O.HOUR
WHERE TEMP.HOUR <= 23
ORDER BY TEMP.HOUR